# coding: utf-8

"""
    Medical System API

    API для керування пацієнтами, лікарями, записами на прийом та медичними записами.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_appointments_get(self) -> None:
        """Test case for appointments_get

        Отримати список записів на прийом
        """
        pass

    def test_appointments_post(self) -> None:
        """Test case for appointments_post

        Створити запис на прийом
        """
        pass

    def test_doctors_get(self) -> None:
        """Test case for doctors_get

        Отримати список лікарів
        """
        pass

    def test_doctors_post(self) -> None:
        """Test case for doctors_post

        Додати нового лікаря
        """
        pass

    def test_login_post(self) -> None:
        """Test case for login_post

        Авторизація користувача
        """
        pass

    def test_patients_get(self) -> None:
        """Test case for patients_get

        Отримати список пацієнтів
        """
        pass

    def test_patients_id_delete(self) -> None:
        """Test case for patients_id_delete

        Видалити пацієнта
        """
        pass

    def test_patients_id_get(self) -> None:
        """Test case for patients_id_get

        Отримати інформацію про пацієнта
        """
        pass

    def test_patients_id_put(self) -> None:
        """Test case for patients_id_put

        Оновити дані пацієнта
        """
        pass

    def test_patients_post(self) -> None:
        """Test case for patients_post

        Додати нового пацієнта
        """
        pass

    def test_records_get(self) -> None:
        """Test case for records_get

        Отримати список медичних записів
        """
        pass

    def test_records_post(self) -> None:
        """Test case for records_post

        Додати медичний запис
        """
        pass

    def test_register_post(self) -> None:
        """Test case for register_post

        Реєстрація нового користувача
        """
        pass


if __name__ == '__main__':
    unittest.main()
