# coding: utf-8

# flake8: noqa
"""
    Medical System API

    API для керування пацієнтами, лікарями, записами на прийом та медичними записами.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
